name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    name: Test Node Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install root dependencies
        run: yarn install --frozen-lockfile

      - name: Run backend tests
        working-directory: packages/node
        run: yarn test --coverage

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: node-backend-coverage
          path: packages/node/coverage
